### ISSUE TITLE
Please, I need some help

### ISSUE THREAD

**Issue by leiserfg** [bjvanst/zmk-config#1]
Hi! I'm trying to set my own sweep, but I'm still a bit lost with only 34 keys and zmk so I'm trying to have a look at other people's configs to gather ideas. Till now your config seems my favorite one, but I'll have to tweak it as I plan to keep using qwerty at least for a while, so I removed the default layer and replaced it with the `querty` one, but I don't understand your `hdalte_layer` so if you were so nice as to explain me why/how do you use it for so I know if it's useful for me as well.

**Comment by bjvanst** [comment]
The whole keymap is in flux but I've been playing around with different keyboard layouts.  The default in the current keymap is colemak-dh and hdalte is Hands Down's Alt-Ex variant:

https://sites.google.com/alanreiser.com/handsdown/home/hands-down-alt#h.7nqnh6ai9dli

You can remove it!

**Comment by leiserfg** [comment]
Thanks a lot!
